"""Seed knowledge base for the game recommendation demo."""

GAMES = [
    {
        "id": "stardew_valley",
        "title": "Stardew Valley",
        "genres": ["Simulation", "Casual"],
        "moods": ["Santai", "Stres"],
        "platforms": ["PC", "Console", "Mobile"],
        "modes": ["SinglePlayer", "Coop"],
        "difficulty": "Mudah",
        "durations": ["Sedang", "Panjang"],
    },
    {
        "id": "minecraft",
        "title": "Minecraft",
        "genres": ["Adventure", "Sandbox"],
        "moods": ["Eksploratif", "Sosial", "Bosan"],
        "platforms": ["PC", "Console", "Mobile"],
        "modes": ["SinglePlayer", "Multiplayer", "Coop"],
        "difficulty": "Sedang",
        "durations": ["Sedang", "Panjang"],
    },
    {
        "id": "valorant",
        "title": "Valorant",
        "genres": ["FPS"],
        "moods": ["Kompetitif", "Sosial"],
        "platforms": ["PC"],
        "modes": ["Multiplayer"],
        "difficulty": "Sulit",
        "durations": ["Singkat", "Sedang"],
    },
    {
        "id": "genshin_impact",
        "title": "Genshin Impact",
        "genres": ["RPG", "Adventure"],
        "moods": ["Eksploratif", "Santai"],
        "platforms": ["PC", "Mobile", "Console"],
        "modes": ["SinglePlayer", "Coop"],
        "difficulty": "Sedang",
        "durations": ["Sedang", "Panjang"],
    },
    {
        "id": "candy_crush",
        "title": "Candy Crush",
        "genres": ["Puzzle", "Casual"],
        "moods": ["Bosan", "Santai"],
        "platforms": ["Mobile"],
        "modes": ["SinglePlayer"],
        "difficulty": "Mudah",
        "durations": ["Singkat"],
    },
    {
        "id": "overcooked_2",
        "title": "Overcooked 2",
        "genres": ["Simulation", "Party"],
        "moods": ["Sosial", "Bosan"],
        "platforms": ["PC", "Console"],
        "modes": ["Coop", "Multiplayer"],
        "difficulty": "Sedang",
        "durations": ["Singkat", "Sedang"],
    },
    {
        "id": "the_witcher_3",
        "title": "The Witcher 3",
        "genres": ["RPG", "Adventure"],
        "moods": ["Eksploratif"],
        "platforms": ["PC", "Console"],
        "modes": ["SinglePlayer"],
        "difficulty": "Sedang",
        "durations": ["Panjang"],
    },
    {
        "id": "animal_crossing",
        "title": "Animal Crossing",
        "genres": ["Simulation", "Casual"],
        "moods": ["Santai", "Stres"],
        "platforms": ["Console"],
        "modes": ["SinglePlayer", "Multiplayer"],
        "difficulty": "Mudah",
        "durations": ["Sedang"],
    },
    {
        "id": "league_of_legends",
        "title": "League of Legends",
        "genres": ["MOBA", "Strategy"],
        "moods": ["Kompetitif", "Sosial"],
        "platforms": ["PC"],
        "modes": ["Multiplayer"],
        "difficulty": "Sulit",
        "durations": ["Sedang", "Panjang"],
    },
    {
        "id": "counter_strike_2",
        "title": "Counter-Strike 2",
        "genres": ["FPS"],
        "moods": ["Kompetitif"],
        "platforms": ["PC"],
        "modes": ["Multiplayer"],
        "difficulty": "Sulit",
        "durations": ["Singkat", "Sedang"],
    },
    {
        "id": "apex_legends",
        "title": "Apex Legends",
        "genres": ["FPS", "BattleRoyale"],
        "moods": ["Kompetitif", "Sosial"],
        "platforms": ["PC", "Console"],
        "modes": ["Multiplayer"],
        "difficulty": "Sulit",
        "durations": ["Singkat", "Sedang"],
    },
    {
        "id": "terraria",
        "title": "Terraria",
        "genres": ["Adventure", "Sandbox"],
        "moods": ["Eksploratif", "Bosan"],
        "platforms": ["PC", "Console", "Mobile"],
        "modes": ["SinglePlayer", "Multiplayer", "Coop"],
        "difficulty": "Sedang",
        "durations": ["Sedang", "Panjang"],
    },
    {
        "id": "hollow_knight",
        "title": "Hollow Knight",
        "genres": ["Adventure", "Metroidvania"],
        "moods": ["Eksploratif"],
        "platforms": ["PC", "Console"],
        "modes": ["SinglePlayer"],
        "difficulty": "Sulit",
        "durations": ["Panjang"],
    },
    {
        "id": "civilization_vi",
        "title": "Civilization VI",
        "genres": ["Strategy"],
        "moods": ["Kompetitif", "Eksploratif"],
        "platforms": ["PC", "Console", "Mobile"],
        "modes": ["SinglePlayer", "Multiplayer"],
        "difficulty": "Sedang",
        "durations": ["Panjang"],
    },
    {
        "id": "the_sims_4",
        "title": "The Sims 4",
        "genres": ["Simulation", "Casual"],
        "moods": ["Santai", "Bosan"],
        "platforms": ["PC", "Console"],
        "modes": ["SinglePlayer"],
        "difficulty": "Mudah",
        "durations": ["Sedang", "Panjang"],
    },
    {
        "id": "unpacking",
        "title": "Unpacking",
        "genres": ["Puzzle", "Casual"],
        "moods": ["Santai", "Stres"],
        "platforms": ["PC", "Console"],
        "modes": ["SinglePlayer"],
        "difficulty": "Mudah",
        "durations": ["Singkat", "Sedang"],
    },
    {
        "id": "journey",
        "title": "Journey",
        "genres": ["Adventure", "Casual"],
        "moods": ["Santai", "Stres", "Eksploratif"],
        "platforms": ["PC", "Console", "Mobile"],
        "modes": ["SinglePlayer", "Multiplayer"],
        "difficulty": "Mudah",
        "durations": ["Singkat", "Sedang"],
    },
    {
        "id": "among_us",
        "title": "Among Us",
        "genres": ["Party", "SocialDeduction"],
        "moods": ["Sosial", "Bosan"],
        "platforms": ["PC", "Mobile", "Console"],
        "modes": ["Multiplayer"],
        "difficulty": "Mudah",
        "durations": ["Singkat"],
    },
]

MOODS = ["Santai", "Kompetitif", "Stres", "Bosan", "Eksploratif", "Sosial"]
GENRES = sorted({genre for game in GAMES for genre in game["genres"]})
PLATFORMS = sorted({platform for game in GAMES for platform in game["platforms"]})
MODES = sorted({mode for game in GAMES for mode in game["modes"]})
DURATIONS = ["Singkat", "Sedang", "Panjang"]
DIFFICULTIES = ["Mudah", "Sedang", "Sulit"]
